# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Rizwan Patel
title: Expert Software Engineer
email: rizwanbpatel@gmail.com
website: www.github.com/rizwanbpatel

# Social links
twitter_username: rizwanbpatel
github_username:  rizwanbpatel
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: rizwanbpatel
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profle.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rizwan and I'm an Exper Software Engineer at TomTom. I am a polyglot. Have experience making software and leading teams. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Java</mark> and <mark>Building Ideas in BitBucket</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networking and software engineering some of my other interests and hobbies are:
   - Attending Local MeetUps
   - Travel
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
